name: Deploy Hugo site

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  call:
    name: Call workflow
    uses: AnotherCanis/actions-deploy/.github/workflows/deploy.yaml@main
    with:
      hugo-version: '0.131.0'
      enforce-https: true
